# Generated by Django 6.0.5 on 2026-06-03 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroCosecha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('bloque', models.CharField(max_length=50)),
                ('variedad', models.CharField(choices=[('clavel-rojo', 'Clavel Rojo'), ('clavel-rosa', 'Clavel Rosa'), ('clavel-blanco', 'Clavel Blanco'), ('clavel-morado', 'Clavel Morado'), ('clavel-naranja', 'Clavel Naranja'), ('clavel-bicolor', 'Clavel Bicolor')], max_length=20)),
                ('cantidad', models.IntegerField()),
                ('responsable', models.CharField(max_length=100)),
                ('condicion', models.CharField(choices=[('exportacion', 'Exportación'), ('fanci', 'Fanci'), ('nacional', 'Nacional'), ('basura', 'Basura')], max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-fecha_registro'],
            },
        ),
    ]
