# Generated by Django 6.0.5 on 2026-06-03 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_empleado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='rol',
        ),
        migrations.AddField(
            model_name='empleado',
            name='puesto',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='telefono',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
