# Generated by Django 6.0.6 on 2026-06-30 02:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_remove_empleado_rol_empleado_puesto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_cat', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_cat', models.CharField(max_length=100)),
                ('descripcion_cat', models.TextField(blank=True)),
                ('estado_cat', models.CharField(default='activo', max_length=20)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['nombre_cat'],
            },
        ),
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id_insu', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_insu', models.CharField(max_length=100)),
                ('cantidad_stock', models.IntegerField(default=0)),
                ('fecha_ingreso', models.DateField()),
                ('estado_insu', models.CharField(default='activo', max_length=20)),
                ('proveedor', models.CharField(blank=True, max_length=100)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='insumos', to='dashboard.categoria')),
            ],
            options={
                'verbose_name': 'Insumo',
                'verbose_name_plural': 'Insumos',
                'ordering': ['nombre_insu'],
            },
        ),
    ]
