# Generated by Django 6.0.5 on 2026-06-30 04:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_remove_empleado_rol_empleado_puesto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_cat', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_cat', models.CharField(max_length=100)),
                ('descripcion_cat', models.TextField(blank=True, null=True)),
                ('estado_cat', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'categoria',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id_prov', models.AutoField(primary_key=True, serialize=False)),
                ('ruc_prov', models.CharField(max_length=13, unique=True)),
                ('nombre_prov', models.CharField(max_length=100)),
                ('contacto_prov', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono_prov', models.CharField(max_length=20)),
                ('correo_prov', models.EmailField(blank=True, max_length=254, null=True)),
                ('direccion_prov', models.TextField(blank=True, null=True)),
                ('estado_prov', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'proveedor',
            },
        ),
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id_insu', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_insu', models.CharField(max_length=100)),
                ('cantidad_stock', models.IntegerField(default=0)),
                ('fecha_ingreso', models.DateField(auto_now_add=True)),
                ('estado_insu', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(blank=True, db_column='categoria_id_cat', null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.categoria')),
                ('proveedor', models.ForeignKey(blank=True, db_column='Proveedor_id_prov', null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.proveedor')),
            ],
            options={
                'db_table': 'consumo',
            },
        ),
    ]
