# Generated by Django 6.0.6 on 2026-07-01 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='direccion',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='fecha_ingreso',
            field=models.DateField(),
        ),
    ]
